run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - gen
    - frontend
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - noctx
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/maximcapsa/devops-full-project
  revive:
    rules:
      - name: exported
        disabled: true
