// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         pgtype.UUID
	Status     string
	TotalCents int64
	CreatedAt  time.Time
}

type OrderItem struct {
	OrderID   pgtype.UUID
	ProductID pgtype.UUID
	Quantity  int32
}
