// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	Type      string
	Message   string
	CreatedAt time.Time
}
