// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (order_id, type, message)
VALUES ($1, $2, $3)
ON CONFLICT (order_id, type) DO NOTHING
`

type InsertNotificationParams struct {
	OrderID pgtype.UUID
	Type    string
	Message string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification, arg.OrderID, arg.Type, arg.Message)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, order_id, type, message, created_at
FROM notifications
WHERE order_id = $1
ORDER BY created_at
`

func (q *Queries) ListNotifications(ctx context.Context, orderID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
