// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProcessedOrder = `-- name: GetProcessedOrder :one
SELECT result, reason
FROM processed_orders
WHERE order_id = $1
`

type GetProcessedOrderRow struct {
	Result string
	Reason string
}

func (q *Queries) GetProcessedOrder(ctx context.Context, orderID pgtype.UUID) (GetProcessedOrderRow, error) {
	row := q.db.QueryRow(ctx, getProcessedOrder, orderID)
	var i GetProcessedOrderRow
	err := row.Scan(&i.Result, &i.Reason)
	return i, err
}

const getStock = `-- name: GetStock :one
SELECT product_id, available, reserved
FROM stock
WHERE product_id = $1
`

func (q *Queries) GetStock(ctx context.Context, productID pgtype.UUID) (Stock, error) {
	row := q.db.QueryRow(ctx, getStock, productID)
	var i Stock
	err := row.Scan(&i.ProductID, &i.Available, &i.Reserved)
	return i, err
}

const getStockForUpdate = `-- name: GetStockForUpdate :one
SELECT product_id, available, reserved
FROM stock
WHERE product_id = $1
FOR UPDATE
`

func (q *Queries) GetStockForUpdate(ctx context.Context, productID pgtype.UUID) (Stock, error) {
	row := q.db.QueryRow(ctx, getStockForUpdate, productID)
	var i Stock
	err := row.Scan(&i.ProductID, &i.Available, &i.Reserved)
	return i, err
}

const insertProcessedOrder = `-- name: InsertProcessedOrder :exec
INSERT INTO processed_orders (order_id, result, reason)
VALUES ($1, $2, $3)
`

type InsertProcessedOrderParams struct {
	OrderID pgtype.UUID
	Result  string
	Reason  string
}

func (q *Queries) InsertProcessedOrder(ctx context.Context, arg InsertProcessedOrderParams) error {
	_, err := q.db.Exec(ctx, insertProcessedOrder, arg.OrderID, arg.Result, arg.Reason)
	return err
}

const reserveStock = `-- name: ReserveStock :exec
UPDATE stock
SET available = available - $1,
    reserved  = reserved + $1
WHERE product_id = $2
`

type ReserveStockParams struct {
	Qty       int32
	ProductID pgtype.UUID
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) error {
	_, err := q.db.Exec(ctx, reserveStock, arg.Qty, arg.ProductID)
	return err
}
