// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessedOrder struct {
	OrderID   pgtype.UUID
	Result    string
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type Stock struct {
	ProductID pgtype.UUID
	Available int32
	Reserved  int32
}
