// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          pgtype.UUID
	Name        string
	Description string
	PriceCents  int64
	CreatedAt   time.Time
}
